export const WORK_SPACE = '/board'
export const REGISTRATION = '/registration'
export const LOGIN = '/login'
export const UPDATE_EMAIL = '/user/email'
export const USER = '/user'
export const USERS = '/users'
export const ONE_USERS = '/user/:id'
export const HOME_PAGE = '/'
export const HELLO_PAGE = '/'
export const AVATAR = '/avatar'
export const BOARD_WINDOW = '/board/:id/column'

export const URL_HOME_PAGE = 'http://localhost:3005'