
export const typesOfAction = {
  REGISTRATION_USER: 'REGISTRATION_USER',
  UPDATE_USER_EMAIL: 'UPDATE_USER_EMAIL',
  GET_ONE_USER: 'GET_ONE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  LOGIN_USER: 'LOGIN_USER',
  GET_TOKEN: 'GET_TOKEN',
};

export const modesOfLogin = {
  AUTHORIZATION: 'AUTHORIZATION',
  REGISTRATION: 'REGISTRATION',
};
// export const REGISTRATION_USER_FALSE = 'REGISTRATION_USER_FALSE'
// export const REGISTRATION_USER_SUCCESS = 'REGISTRATION_USER_SUCCESS'

// export const 
// export const UPDATE_USER_EMAIL_FALSE = 'UPDATE_USER_EMAIL_FALSE'
// export const UPDATE_USER_EMAIL_SUCCESS = 'UPDATE_USER_EMAIL_SUCCESS'
    
// export const GET_ALL_USERS = 'GET_ALL_USERS'
// export const GET_ALL_USERS_FALSE = 'GET_ALL_USERS_FALSE'
// export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'

// export const 
// export const GET_ONE_USER_FALSE = 'GET_ONE_USER_FALSE'
// export const GET_ONE_USER_SUCCESS = 'GET_ONE_USER_SUCCESS'

// export const 
// export const UPDATE_USER_FALSE = 'UPDATE_USER_FALSE'
// export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

// export const 
// export const DELETE_USER_FALSE = 'DELETE_USER_FALSE'
// export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'

// export const 
// export const LOGIN_USER_FALSE = 'LOGIN_USER_FALSE'
// export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'

// export const 
// export const GET_TOKEN_FALSE = 'GET_TOKEN_FALSE'
// export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS'