
export const REGISTRATION_USER = 'REGISTRATION_USER'
export const REGISTRATION_USER_FALSE = 'REGISTRATION_USER_FALSE'
export const REGISTRATION_USER_SUCCESS = 'REGISTRATION_USER_SUCCESS'

export const UPDATE_USER_EMAIL = 'UPDATE_USER_EMAIL'
export const UPDATE_USER_EMAIL_FALSE = 'UPDATE_USER_EMAIL_FALSE'
export const UPDATE_USER_EMAIL_SUCCESS = 'UPDATE_USER_EMAIL_SUCCESS'
    
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const GET_ALL_USERS_FALSE = 'GET_ALL_USERS_FALSE'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'

export const GET_ONE_USER = 'GET_ONE_USER'
export const GET_ONE_USER_FALSE = 'GET_ONE_USER_FALSE'
export const GET_ONE_USER_SUCCESS = 'GET_ONE_USER_SUCCESS'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_FALSE = 'UPDATE_USER_FALSE'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_FALSE = 'DELETE_USER_FALSE'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_FALSE = 'LOGIN_USER_FALSE'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'

export const GET_TOKEN = 'GET_TOKEN'
export const GET_TOKEN_FALSE = 'GET_TOKEN_FALSE'
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS'

