
export const REGISTRATION_USER = 'REGISTRATION_USER'
export const REGISTRATION_USER_FALSE = 'REGISTRATION_USER_FALSE'
export const REGISTRATION_USER_SUCCES = 'REGISTRATION_USER_SUCCES'

export const UPDATE_USER_EMAIL = 'UPDATE_USER_EMAIL'
export const UPDATE_USER_EMAIL_FALSE = 'UPDATE_USER_EMAIL_FALSE'
export const UPDATE_USER_EMAIL_SACCES = 'UPDATE_USER_EMAIL_SACCES'
    
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const GET_ALL_USERS_FALSE = 'GET_ALL_USERS_FALSE'
export const GET_ALL_USERS_SUCCES = 'GET_ALL_USERS_SUCCES'

export const GET_ONE_USER = 'GET_ONE_USER'
export const GET_ONE_USER_FALSE = 'GET_ONE_USER_FALSE'
export const GET_ONE_USER_SACCES = 'GET_ONE_USER_SACCES'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_FALSE = 'UPDATE_USER_FALSE'
export const UPDATE_USER_SUCCES = 'UPDATE_USER_SUCCES'

export const DELET_USER = 'DELETE_USER'
export const DELET_USER_FLASE = 'DELET_USER_FLASE'
export const DELET_USER_SACCES = 'DELET_USER_SACCES'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_FALSE = 'LOGIN_USER_FALSE'
export const LOGIN_USER_SUCCES = 'LOGIN_USER_SUCCES'

export const GET_TOKEN = 'GET_TOKEN'
export const GET_TOKEN_FALSE = 'GET_TOKEN_FALSE'
export const GET_TOKEN_SUCCES = 'GET_TOKEN_SUCCES'

